development:
  adapter: mysql
  encoding: utf8
  database: learn_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: learn_test
  username: root
  password:
  host: localhost
  
production:
  adapter: mysql
  database: learn_production
  username: rails
  password: thisIStheMOSTsecurePASSWORD
  host: localhost