--- 
- :source: http://gems.github.com
  :name: rubyist-aasm
- :name: hpricot
- :version: ">= 1.2.0"
  :name: rspec
- :version: ">= 1.2.0"
  :name: rspec-rails
- :name: erubis
- :version: 2.3.2
  :name: rails
